# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'LearnOpenGLESWithGPUImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LearnOpenGLESWithGPUImage
  pod 'GPUImage', :path => '../../GPUImage-doc'

  target 'LearnOpenGLESWithGPUImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
