# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

workspace 'Tutorial-13'

target 'LearnOpenGLESWithGPUImage' do
  project './Tutorial-singleLessDraw/singleLessDraw'
  pod 'GPUImage', :path => '../../GPUImage-doc'
end

target 'LearnOpenGLESWithGPUImage' do
  project './Tutorial-singleImageView/singleImageView'
  pod 'GPUImage', :path => '../../GPUImage-doc'
end

target 'LearnOpenGLESWithGPUImage' do
  project './Tutorial-multiImageView/multiImageView'
  pod 'GPUImage', :path => '../../GPUImage-doc'
end
